### ISSUE TITLE
sendByBaseNumber via REST throws an exception

### ISSUE THREAD

**Issue by smhnaji** [Melipayamak/melipayamak-php#5]
Consider the following code:

	use Melipayamak\MelipayamakApi;
	$username = env('MELIPAYAMAK_USERNAME', 'user');
	$password = env('MELIPAYAMAK_PASSWORD', 'pass');
	$api = new MelipayamakApi($username, $password);
	// $sms = $api->sms('soap'); // With this line, it works well
	$sms = $api->sms(); // But it using this method causes an exception
	$to = $receiverMobile;
	$from = 5000.....;

	$message = is_array($message) ? implode(';', $message) : $message;
	$response = $sms->sendByBaseNumber($message, $to, $templateId);
	dd($response);

And the exception...

	"{"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at FinalRest.Controllers.SendController.BaseServiceNumber(JObject paramList)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"} ◀"

Thank you

**Comment by triggergroup** [comment]
Note that `sendByBaseNumber` method has 3 inputs, when you left a required input unmounted (null), such this error occur. Let us know if your problem is solved.

**Comment by khanzadimahdi** [comment]
use the below package if your are in Laravel

https://github.com/tzsk/sms

**Comment by nikandlv** [comment]
Having the same issue, and they dont even bother fixing them. what a shame
This sms service provider is such a mess
had alot of issues with technical and non technical employees

**Comment by triggergroup** [comment]
@nikandlv @smhnaji We don't support `sendByBaseNumber ` in **REST**.

**Comment by triggergroup** [comment]
@nikandlv  I'd like to know when did you contact with developer team before writing such this frustrating comment ?!

**Comment by triggergroup** [comment]
> 
> 
> Having the same issue, and they dont even bother fixing them. what a shame
> This sms service provider is such a mess
> had alot of issues with technical and non technical employees

I'd like to know when did you contact with developer team before writing such this frustrating comment ?!

**Comment by nikandlv** [comment]
So you removed the docs today https://github.com/Melipayamak/melipayamak-php/commit/3aee4d6c40f612f8afc036570bbc240614a8bae6 after half of a year the issue was opened?

**Comment by Melipayamak-Team** [comment]
> Consider the following code:
> 
> ```
> use Melipayamak\MelipayamakApi;
> $username = env('MELIPAYAMAK_USERNAME', 'user');
> $password = env('MELIPAYAMAK_PASSWORD', 'pass');
> $api = new MelipayamakApi($username, $password);
> // $sms = $api->sms('soap'); // With this line, it works well
> $sms = $api->sms(); // But it using this method causes an exception
> $to = $receiverMobile;
> $from = 5000.....;
> 
> $message = is_array($message) ? implode(';', $message) : $message;
> $response = $sms->sendByBaseNumber($message, $to, $templateId);
> dd($response);
> ```
> 
> And the exception...
> 
> ```
> "{"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at FinalRest.Controllers.SendController.BaseServiceNumber(JObject paramList)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"} ◀"
> ```
> 
> Thank you

hi, hope you're doing well
the problem is data types.
you must check your inputs parsing into sendbybasenumber method.
also please bare in mind that $templateId is not defined in your codes and
